I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2774, in script call
    call motomachi
  File "game/script.rpy", line 3939, in script
    show bg dress_shop1 with fade
IOError: Couldn't find file 'walk.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2774, in script call
    call motomachi
  File "game/script.rpy", line 3939, in script
    show bg dress_shop1 with fade
  File "K:\gunyeonsi\renpy\renpy\ast.py", line 1275, in execute
    renpy.exports.with_statement(trans, paired)
  File "K:\gunyeonsi\renpy\renpy\exports.py", line 1381, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "K:\gunyeonsi\renpy\renpy\display\core.py", line 2096, in do_with
    clear=clear)
  File "K:\gunyeonsi\renpy\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "K:\gunyeonsi\renpy\renpy\display\core.py", line 2825, in interact_core
    renpy.audio.audio.interact()
  File "K:\gunyeonsi\renpy\renpy\audio\audio.py", line 930, in interact
    periodic()
  File "K:\gunyeonsi\renpy\renpy\audio\audio.py", line 864, in periodic
    c.periodic()
  File "K:\gunyeonsi\renpy\renpy\audio\audio.py", line 403, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "K:\gunyeonsi\renpy\renpy\audio\audio.py", line 67, in load
    rv = renpy.loader.load(fn)
  File "K:\gunyeonsi\renpy\renpy\loader.py", line 543, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'walk.wav'.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
gungrave_project 0.0
